---
abstract: 'LDAP model class for Catalyst'
author:
  - '=over 4'
build_requires:
  Catalyst::Test: 0
  Data::Dumper: 0
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-LDAP
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Catalyst: 5.62
  Catalyst::Model: 0
  Class::Accessor::Fast: 0
  Data::Page: 0
  MRO::Compat: 0
  Net::LDAP: 0.34
  Net::LDAP::Constant: 0
  Net::LDAP::Control::Sort: 0
  Net::LDAP::Control::VLV: 0
  Net::LDAP::Entry: 0
  Net::LDAP::Search: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/trunk/Catalyst-Model-LDAP/
version: 0.17
